version: '3'
services:
  app:
    build: ./app
    command: ["bundle", "exec", "unicorn", "-p", "9292", "-c", "/tmp/unicorn.rb"]
    volumes:
      - ./app/:/app
      - ./config/unicorn.rb/:/tmp/unicorn.rb
  proxy:
    image: nginx
    command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - app


